### PR TITLE
Add amqp routing key

### PR DESCRIPTION
**Pull request by korol8484**

### CODE REVIEW

**Comment by wolfy-j** [comment]
Looks OK to me. But GHA died again sounds like...

**Comment by 48d90782** [comment]
@korol8484 Also, please, add some description, on how to use `routing key` for documentation. Thanks.

**Comment by 48d90782** [comment]
@korol8484 You can use a local test environment. Just `cd` into the `tests` folder, exec `docker-compose up -d` and exec from the root - `make test`. FYI, you need to manually clean up exchanges (only for the RabbitMQ) between test executions.

**Comment by 48d90782** [comment]
Hey @korol8484, just friendly ping, any progress here?

**Comment by 48d90782** [comment]
@korol8484 Closing due to inactivity.

**Pull request closed without merging**
