### PR TITLE
[WIP] AMQP integration

### PR DESCRIPTION
**Pull request by Alex-Bond**
Hey!

I created AMQP integration. At this moment it doesn't support sending to exchanges but does support binding.

Waiting for @wolfy-j code review.

### CODE REVIEW

**Comment by wolfy-j** [comment]
LOL, i have been planning to release AMQP support this week with reconnects and proper queue routing. :) See amqp branch, it's in process :)

Thank you for your work :)

**Comment by wolfy-j** [comment]
Integration itself is not super easy since we have to properly handle connection issues and reconnects.

**Comment by wolfy-j** [comment]
Sorry about that :) I did not expect anyone to hop on this task :)

**Comment by Alex-Bond** [comment]
@wolfy-j anyway, you can use any parts of my code if u need :)

**Comment by wolfy-j** [comment]
@Alex-Bond i want to use your queue/exchange parameter mapping later but you can take a look on current AMQP implementation in master right now. It has been a challenge to make reliable connection manages without spawning more than 2 connections to AMQP per application (channel multiplexing).

**Pull request closed without merging**
